FROM ubuntu:latest

RUN mkdir /文件夹名

COPY ./程序架包名-0.0.1-SNAPSHOT.jar /文件夹名

#JAVA1.8

ADD ./jdk-8u91-linux-x64.tar.gz /usr/local/

RUN ln -s /usr/local/jdk1.8.0_91 /usr/local/java1.8

ENV JAVA_HOME /usr/local/java1.8

ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

ENV PATH $PATH:$JAVA_HOME/bin

RUN echo "JAVA_HOME=/usr/local/java1.8\nCLASSPATH=JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar\nPATH=$PATH:$JAVA_HOME/bin" >> /etc/profile ##run命令可以有多个

WORKDIR /文件夹名 ##工作文件夹

CMD ["java","-jar","/文件夹名/程序架包名-0.0.1-SNAPSHOT.jar(架包路径)"]: ##CMD命令只能有一个，有多个也只会执行一个,该命令为执行该架包

ENTRYPOINT ["java","-jar","/文件夹名/程序架包名-0.0.1-SNAPSHOT.jar（架包路径）"]
